### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by ATNewHope** [raghavyuva/LucaMail#10]
Nice client, I'd like to recommend it to my friends once POP3 is supported and localization is supported.

One of my friend would like to contribute in translation, I mean, if he could. 
He did some translations for other projects on crowdin, which is free for public projects. (Of course, it's not the only method.)

**Comment by raghavyuva** [comment]
@ATNewHope thanks for trying it out, I'll definitely implement these features in next version

**Comment by sonalder-darlene** [comment]
Will kindly contribute for localization (french)^^
