### ISSUE TITLE
Redundancy on macOS app

### ISSUE THREAD

**Issue by sonalder-darlene** [raghavyuva/LucaMail#11]
On the login page (fresh install) I get a Windows menu _ [ ] X on the top right and the three coloured dots on the top left they also aren't aligned. I would remove the windows style menu on macOS so it blend better with the other apps !

Screenshot :
<img width="791" alt="image" src="https://user-images.githubusercontent.com/73744170/159749544-701244a9-c31d-46ca-923b-2818f0726e94.png">

**Comment by raghavyuva** [comment]
I tried it , thanks for noticing, I'll correct it out
