### ISSUE TITLE
Login different than email

### ISSUE THREAD

**Issue by martinkoutecky** [raghavyuva/LucaMail#13]
I can't set LucaMail up because my IMAP/SMTP login is "name" whereas my email is "name@domain.tld". I know this is atypical but can't do anything about, so Luca should probably have some "advanced settings" dialogue where "email" and "login" can be set separately.

**Comment by ATNewHope** [comment]
Oh, I may get it. 
Normally, the <AccountName> for logging in an IMAP server is "name@domain.tld", which is exactly the same as the <EmailAddress>.
However, in some situation, while email address is still "name@domain.tld", the <AccountName> for IMAP becomes "name". In such case, the attempt to login the IMAP server with configured <AccountName> = "name@domain.tld" would fail.

**Comment by ATNewHope** [comment]
Oh, I may get it.
Normally, the AccountName for logging in an IMAP server is "name@domain.tld", which is exactly the same as the EmailAddress.
However, in some situation, while EmailAddress is still "name@domain.tld", the AccountName for IMAP becomes "name". In such case, the attempt to login the IMAP server with configured AccountName = EmailAddress = "name@domain.tld" would fail.

**Comment by Mara-Li** [comment]
Hello! I have the same issue.
My email is something like `myname.mylastname@domain` but my login is my university number (something like `123564789`). So, the connection fail :(
