### ISSUE TITLE
Automatic Account Configuration

### ISSUE THREAD

**Issue by TristanAppDev** [raghavyuva/LucaMail#4]
From an user's point of view it would be a massive improvement in UX if LucaMail had Automatic Account Configuration.
You provide Username, Mail and Password and LucaMail determines all your connection details.

**Comment by Gh0stz0x** [comment]
I think they could reuse the data from https://github.com/deltachat/provider-db 🤔

**Comment by Lunarequest** [comment]
They could also use https://autoconfig.thunderbird.net/ which is what thunderbird and fairmail use.

**Comment by raghavyuva** [comment]
> They could also use https://autoconfig.thunderbird.net/ which is what thunderbird and fairmail use.

the link shared is not reachable

**Comment by Lunarequest** [comment]
The algorithm thunderbird uses is like this
1. Check  `https://autoconfig.<domain>/mail/config-v1.1.xml?emailaddress=<address>`
2. Check Mozilla's own ISPDB at `https://autoconfig.thunderbird.net/v1.1/<domain> (also look up domain's MX records)`
3.  Finally try some common names like `imap.<domain>` or `mail.<domain>`

**Comment by Lunarequest** [comment]
An example of a valid autoconfig url form thunderbird.net would be 
https://autoconfig.thunderbird.net/v1.1/gmail.com

**Comment by Lunarequest** [comment]
Any reason this isn't planed? Every major email client has this feature

**Comment by raghavyuva** [comment]
Development is halted as of now, looking for contributors to keep up to date with the project. sorry for the inconvenience caused.

**Comment by Lunarequest** [comment]
I don't mind helping updating deps if that's what you mean

**Comment by raghavyuva** [comment]
Sure, let's connect over discord to discuss further, please join and ping me.
